---
- name: download the zipped artifact
  shell: |
    echo $CIRCLE_TOKEN 
    echo $CIRCLE_BUILD_NUM
    cd backend
    curl -H "Circle-Token: $CIRCLE_TOKEN " https://circleci.com/api/v1.1/project/github/jmpberlin/testify/$CIRCLE_BUILD_NUM/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
- name: run the backend
  shell: |
    cd backend
    chmod +x server
    ./server --DB_NAME=$DB_NAME --DB_PORT=$DB_PORT --DB_HOST=$DB_HOST --DB_USER=$DB_USER --DB_PASSWORD=$DB_PASSWORD
  environment:
    CIRCLE_TOKEN: "{{ lookup('env', 'CIRCLE_TOKEN')}}"
    CIRCLE_BUILD_NUM: "{{ lookup('env', 'CIRCLE_BUILD_NUM')}}"
    DB_NAME: "{{ lookup('env', 'DB_NAME')}}"
    DB_PORT: "{{ lookup('env', 'DB_PORT')}}"
    DB_HOST: "{{ lookup('env', 'DB_HOST')}}"
    DB_USER: "{{ lookup('env', 'DB_USER')}}"
    DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD')}}"
#
