jobs:
  build:
    executor:
      name: go/default
      tag: '1.17'
    steps:
      - checkout
      # - go/load-cache
      # - go/mod-download
      # - go/save-cache
      - run:
          name: 'trying to build the backend'
          command: |
            go version
            pwd
            ls -la 
            cd backend
            go build ./cmd/web/*.go -o server
            mv ./server ..
            cd .. 
            ls -la
      - run:
          name: move binary to artifact
          command: |
            mkdir artifacts
            mv ~/project/server ~/project/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - project/artifacts
  configure the server:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - store_artifacts:
          path: ~/project/artifacts
      - run:
          name: download and run the server on the ec2-instance
          command: |
            pwd 
            cd artifacts
            ls -ls 
            cd .. 
            apk add --update ansible
            ansible-playbook -vv -i ~/project/.circleci/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml
orbs:
  go: circleci/go@1.7.1
  python: circleci/python@2.1.1
version: 2.1
workflows:
  main:
    jobs:
      - build
      - configure the server:
          requires: [build]
#             # ansible-playbook -vv -i ~/project/.circleci/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml
# cat ~/project/.circleci/ansible/deploy-backend.yml
